# Generated by Django 4.2.29 on 2026-03-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='First uploaded image is set as main; can be changed in admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_as_main', to='store.productimage'),
        ),
    ]
