# Generated by Django 4.2.29 on 2026-03-11 00:00

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Original price shown with a strikethrough when the product is on sale.',
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(
                default=False,
                help_text='When enabled, the product card shows a Sale badge and compare-at price.',
            ),
        ),
    ]

