# Generated by Django 4.2.29 on 2026-03-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='store_passw_user_id_08977e_idx',
            old_name='store_passw_user_id_7d7f45_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='store_passw_expires_82b57f_idx',
            old_name='store_passw_expires_1b0f5d_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products appear in the carousel on the home page.'),
        ),
    ]
